<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="geometry3Sharp" Version="1.0.324" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../Output/**/*">
      <LogicalName>Adv2Obj.ReferenceOutputs/%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
